### ISSUE TITLE
Atom Beta 1.13.x Selector Deprecations

### ISSUE THREAD

**Issue by docrinehart** [heisian/hacking-the-kernel-ui#2]
In the upcoming atom version, there are a number of deprecations to the selectors for styling. Additionally, I noticed with the recent atom beta update, the line number column is only styles for the currently active line. All other line numbers have a white background.

I haven't verified it, but I think that may be due to the selector deprecations.

**Comment by heisian** [comment]
I apologize for quite a delayed response.  I've only been using the production Atom builds.

I'm a bit confused - a post on their blog in Dec. 2015 states that Atom 1.3 is out and Atom 1.4-beta is available as well, however the latest production build I just downloaded is 1.12.6.  Is it out or is it not out or..?

I'm a bit hesitant to run the beta in parallel since this dev box I need to keep pretty consistent for my daily work.

**Comment by docrinehart** [comment]
Oops, my bad. Made a typo there. Should have been Beta 1.13 (fixing it now)
And if you need to stay on top of it for atom prod builds only, by all means - it's your project. ^_^ But at least now you have something tracking that when 1.13.x comes out, there'll be some updates needed. If I get some time, I'll see if I can fork it and fix the issue for you.

**Comment by heisian** [comment]
Okay, I'll try to get at it this week or next, thank u for pointing it out :]

**Comment by heisian** [comment]
Seems like the only issue was the gutter background being white - plz let me know if you run into any other weirdness!

**Comment by docrinehart** [comment]
Will do. Thanks ^_^
